// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEBODEVI.Data;

#nullable disable

namespace WEBODEVI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221225094102_DatabaseSetup")]
    partial class DatabaseSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEBODEVI.Models.Uye", b =>
                {
                    b.Property<int>("UyeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UyeID"));

                    b.Property<string>("UyeAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UyeMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UyeSifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UyeSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UyeID");

                    b.ToTable("Uyeler");
                });
#pragma warning restore 612, 618
        }
    }
}
